package controller;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import resource.Inicio;
import util.ValidatorCPF;

public class RecuperarController {
	@FXML
	private Button btnVoltarLogin;
	@FXML
	private TextField idUsuario;
	@FXML
	private TextField idCPF;
	@FXML
	private PasswordField idSenha;
	@FXML
	private PasswordField idConfirmaSenha;
	@FXML
	private Button btnCadastrar;

	@FXML
	private void voltar(Event event) throws Exception {
		Parent root = FXMLLoader.load(getClass().getResource("/view/Login.fxml"));
		Scene scene = new Scene(root);
		Inicio.myStage.setScene(scene);
	}
	
	@FXML
	private void tbCpf() {
		new ValidatorCPF(idCPF);
	}
	
	// Event Listener on Button[#btnCadastrar].onAction
	@FXML
	public void salvarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
}
