package controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;

public class RecuperarController {
	@FXML
	private Button btnVoltarLogin;
	@FXML
	private TextField idUsuario;
	@FXML
	private TextField idCPF;
	@FXML
	private PasswordField idSenha;
	@FXML
	private PasswordField idConfirmaSenha;
	@FXML
	private Button btnCadastrar;

	// Event Listener on Button[#btnVoltarLogin].onAction
	@FXML
	public void voltar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void voltar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#idCPF].onKeyReleased
	@FXML
	public void tbCpf(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCadastrar].onAction
	@FXML
	public void salvarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
}
